structured-log ^0.2.0 as allowed peer dep version
Wedvich/structured-log-seq-sink pull request #6
Opened 2017-09-27 16:32 UTC by charandas

Now that structured-log has moved on, would it make sense to add the latest minor to peer deps?

2018-08-06 07:18 UTC, SimonCropp commented
@Wedvich this would seem to be a good PR?

2018-08-09 06:22 UTC, nblumhardt commented
Just to chime in, I'm happy to lend a hand here if I can :-) :+1:

2018-08-23 09:44 UTC, Wedvich requested changes

2018-08-23 09:44 UTC, Wedvich commented on package.json
> +    "structured-log": "^0.2.0" || "^0.1.0 || ^0.0.18"
`"^0.2.0" || "^0.1.0 || ^0.0.18"` should be `"^0.2.0 || ^0.1.0 || ^0.0.18"` (note the extra quotes) - wanna fix, then I'll merge in the PR?

2022-08-26 15:55 UTC, closed without merging